import { useState } from "react";
import { PRIORITIES, SKILLS, TASK_STATUSES } from "../data";
import { dateLabel, money } from "../engine";
import { Badge, Button, PageHeading, Panel, Progress } from "../ui";

const toneForStatus = (status) => status === "Done" ? "success" : status === "Blocked" ? "danger" : status === "In Progress" ? "warning" : "neutral";

export function Planner({ state, plan, updateTask, updateProject, addTask }) {
  const [showAdd, setShowAdd] = useState(false);
  const [draft, setDraft] = useState({ title: "", estimatedHours: 8, priority: "Medium", skills: [], dependencies: [], notes: "" });
  const taskById = Object.fromEntries(state.tasks.map((task) => [task.id, task]));
  const toggleSkill = (skill) => setDraft((current) => ({ ...current, skills: current.skills.includes(skill) ? current.skills.filter((item) => item !== skill) : [...current.skills, skill] }));
  const toggleDependency = (id) => setDraft((current) => ({ ...current, dependencies: current.dependencies.includes(id) ? current.dependencies.filter((item) => item !== id) : [...current.dependencies, id] }));
  function submitTask(event) {
    event.preventDefault();
    if (!draft.title.trim() || !draft.skills.length) return;
    addTask({ ...draft, title: draft.title.trim(), estimatedHours: Number(draft.estimatedHours) || 1, status: "To Do", assigneeId: "" });
    setDraft({ title: "", estimatedHours: 8, priority: "Medium", skills: [], dependencies: [], notes: "" });
    setShowAdd(false);
  }
  return <div className="page">
    <PageHeading eyebrow="Auto-planned delivery flow" title="Task planner and dependency map" text="Elite Delivery Intelligence assigns the strongest available person, creates a dependency-aware schedule, and recalculates risk as you change work." action={<Button onClick={() => setShowAdd((value) => !value)}>{showAdd ? "Close task form" : "Add delivery task"}</Button>}/>
    {showAdd && <Panel eyebrow="New scope item" title="Add a task to the delivery plan"><form className="task-form" onSubmit={submitTask}><label>Task title<input required value={draft.title} onChange={(event) => setDraft((current) => ({ ...current, title: event.target.value }))} placeholder="e.g. Stakeholder analytics workshop"/></label><label>Estimated hours<input required type="number" min="1" value={draft.estimatedHours} onChange={(event) => setDraft((current) => ({ ...current, estimatedHours: event.target.value }))}/></label><label>Priority<select value={draft.priority} onChange={(event) => setDraft((current) => ({ ...current, priority: event.target.value }))}>{PRIORITIES.map((priority) => <option key={priority}>{priority}</option>)}</select></label><label className="wide-field">Notes<textarea value={draft.notes} onChange={(event) => setDraft((current) => ({ ...current, notes: event.target.value }))} placeholder="Describe scope, approvals, or delivery constraints." rows="2"/></label><div className="wide-field"><span className="input-label">Required skills</span><div className="skill-picker">{SKILLS.map((skill) => <button type="button" key={skill} className={draft.skills.includes(skill) ? "selected" : ""} onClick={() => toggleSkill(skill)}>{draft.skills.includes(skill) ? "✓ " : "+ "}{skill}</button>)}</div></div><div className="wide-field"><span className="input-label">Depends on</span><div className="dependency-picker">{state.tasks.map((task) => <button type="button" key={task.id} className={draft.dependencies.includes(task.id) ? "selected" : ""} onClick={() => toggleDependency(task.id)}>{draft.dependencies.includes(task.id) ? "✓ " : "+ "}{task.title}</button>)}</div></div><div className="form-actions"><Button type="submit">Add and recalculate plan</Button><Button type="button" variant="outline" onClick={() => setShowAdd(false)}>Cancel</Button></div></form></Panel>}
    <section className="project-settings"><Panel eyebrow="Delivery constraints" title="Project settings"><div className="settings-fields"><label>Client tier<select value={state.project.clientTier} onChange={(event) => updateProject({ clientTier: event.target.value })}><option>Platinum</option><option>Gold</option><option>Standard</option></select></label><label>Priority<select value={state.project.priority} onChange={(event) => updateProject({ priority: event.target.value })}>{PRIORITIES.map((priority) => <option key={priority}>{priority}</option>)}</select></label><label>Target deadline<input type="date" value={state.project.deadline} onChange={(event) => updateProject({ deadline: event.target.value })}/></label><label>Contract value<input type="number" value={state.project.contractValue} onChange={(event) => updateProject({ contractValue: Number(event.target.value) || 0 })}/></label></div></Panel><Panel eyebrow="Dependency signal" title="Planning status"><div className="dependency-summary"><span><b>{plan.schedule.filter((task) => task.status === "Done").length}</b> complete</span><span><b>{plan.blockedTasks.length}</b> blocked</span><span><b>{plan.missingDependencies.length}</b> missing links</span><span><b>{plan.slipDays}</b> deadline-slip days</span></div><p className="hint">Changing a deadline or any task assignment automatically updates the schedule and health score.</p></Panel></section>
    <Panel eyebrow="Auto-planned schedule" title="Task assignments and dates" description="Manual changes are respected; unassigned tasks receive the best-fit staffing recommendation."><div className="schedule-table"><div className="schedule-head"><span>Task and dependencies</span><span>Assignee</span><span>Schedule</span><span>Work</span><span>Cost</span><span>Status</span></div>{plan.schedule.map((task) => <div className={`schedule-row ${task.late ? "late" : ""}`} key={task.id}><div className="task-cell"><div><Badge tone={task.priority.toLowerCase()}>{task.priority}</Badge><strong>{task.title}</strong></div><small>{task.dependencies.length ? `After: ${task.dependencies.map((id) => taskById[id]?.title || "Missing task").join(" · ")}` : "No dependencies"}</small>{task.status === "Blocked" && <em>Blocked: {task.notes || "Needs resolution"}</em>}</div><div><select value={task.assigneeId} onChange={(event) => updateTask(task.id, { assigneeId: event.target.value })}><option value="">Auto assign</option>{state.employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name} · {employee.role}</option>)}</select><small>Skill match {Math.round(task.skillMatch * 100)}%</small></div><div className="schedule-date"><strong>{dateLabel(task.start)} → {dateLabel(task.finish)}</strong><small>{task.late ? "Beyond target deadline" : "Within target window"}</small></div><div><strong>{task.plannedHours}h</strong><small>{task.durationDays} work days</small></div><div><strong>{money(task.cost)}</strong><small>{task.role}</small></div><div><select value={task.status} onChange={(event) => updateTask(task.id, { status: event.target.value })}>{TASK_STATUSES.map((status) => <option key={status}>{status}</option>)}</select><Badge tone={toneForStatus(task.status)}>{task.status}</Badge></div></div>)}</div></Panel>
    <Panel eyebrow="Timeline pressure" title="Planned delivery windows"><div className="timeline-list">{plan.schedule.map((task) => <article key={task.id}><div className="timeline-task"><span className={task.status === "Done" ? "done" : task.status === "Blocked" ? "blocked" : ""}>{task.status === "Done" ? "✓" : task.status === "Blocked" ? "!" : ""}</span><div><strong>{task.title}</strong><small>{task.assignee} · {dateLabel(task.start)} to {dateLabel(task.finish)}</small></div></div><div className="timeline-bar"><i className={task.late ? "late" : task.status === "Done" ? "complete" : ""} style={{ width: `${Math.max(12, Math.min(100, task.plannedHours / 32 * 100))}%` }}/></div><b>{task.late ? "Late risk" : `${task.plannedHours}h`}</b></article>)}</div></Panel>
  </div>;
}
