import { dateLabel, money, percent } from "../engine";
import { Badge, Button, Metric, PageHeading, Panel } from "../ui";

export function Reports({ state, plan, savePlan, removePlan, exportJson, exportText, resetWorkspace }) {
  return <div className="page report-page">
    <PageHeading eyebrow="Delivery governance" title="Reports, saves, and plan history" text="Save a planning snapshot before you share a client update, change staffing, or approve a delivery recovery action." action={<Button onClick={savePlan}>Save plan snapshot</Button>}/>
    <div className="metric-grid report-metrics"><Metric label="Current health" value={plan.risk.health} detail={`${plan.risk.score}/100 risk score`} tone={plan.risk.health === "On track" ? "success" : plan.risk.health === "At risk" ? "warning" : "danger"} icon="◆"/><Metric label="Forecast margin" value={`${plan.margin.toFixed(1)}%`} detail={`${money(plan.profit)} expected profit`} tone={plan.margin >= 30 ? "success" : "warning"} icon="◌"/><Metric label="Planned work" value={`${Math.round(plan.schedule.reduce((sum, task) => sum + task.plannedHours, 0))}h`} detail={`${plan.projectDurationDays} calendar days`} tone="blue" icon="◷"/><Metric label="Critical tasks" value={plan.criticalTasks.length} detail={`${plan.blockedTasks.length} currently blocked`} tone={plan.blockedTasks.length ? "danger" : "ink"} icon="!"/></div>
    <div className="report-grid"><Panel eyebrow="Export delivery plan" title="Share the evidence"><div className="export-actions"><Button onClick={exportText}>Download TXT report</Button><Button variant="outline" onClick={exportJson}>Download JSON plan</Button><Button variant="outline" onClick={() => window.print()}>Print / Save as PDF</Button></div><div className="report-preview"><strong>{state.project.name}</strong><span>Client: {state.project.client}</span><span>Completion forecast: {dateLabel(plan.completionDate)}</span><span>Forecast delivery cost: {money(plan.forecastCost)}</span><span>Recommended action: {plan.recommendations[0]?.title}</span></div></Panel><Panel eyebrow="Data management" title="Prototype workspace"><div className="data-actions"><p>All demo changes are kept only in this browser until you export them or connect a production database.</p><Button variant="outline" onClick={resetWorkspace}>Reset demo workspace</Button></div><div className="audit-summary"><span>Brand</span><b>Elite Era Development L.L.C</b><span>Author</span><b>Hira Khyzer</b><span>Brand color</span><b>#f4af00</b></div></Panel></div>
    <Panel eyebrow="Saved planning decisions" title="Plan snapshot library" description="Use saved snapshots to compare delivery decisions over time.">{state.savedPlans.length ? <div className="snapshot-list"><div className="snapshot-head"><span>Saved plan</span><span>Health</span><span>Completion</span><span>Cost</span><span>Margin</span><span/></div>{state.savedPlans.map((snapshot) => <div className="snapshot-row" key={snapshot.id}><div><strong>{snapshot.projectName}</strong><small>{snapshot.createdAt}</small></div><Badge tone={snapshot.health === "On track" ? "success" : snapshot.health === "At risk" ? "warning" : "danger"}>{snapshot.health}</Badge><span>{dateLabel(snapshot.completionDate)}</span><span>{money(snapshot.forecastCost)}</span><span>{percent(snapshot.margin)}</span><button onClick={() => removePlan(snapshot.id)}>Remove</button></div>)}</div> : <div className="empty-report"><i>▤</i><strong>No saved snapshots yet</strong><p>Save the current delivery plan before testing a new scenario or sharing a status update.</p></div>}</Panel>
    <Panel eyebrow="Current decision memo" title="What the delivery lead should communicate"><div className="memo"><div><span>Client-safe update</span><p>The project is currently <b>{plan.risk.health.toLowerCase()}</b>. The next visible milestone is scheduled for {dateLabel(plan.schedule.find((task) => task.status !== "Done")?.finish)}. The delivery team is actively tracking dependencies and capacity.</p></div><div><span>Internal action</span><p>{plan.recommendations[0]?.detail}</p></div><div><span>Commercial guardrail</span><p>Forecast cost is {money(plan.forecastCost)} against a {money(state.project.contractValue)} contract. Maintain change control for additional scope.</p></div></div></Panel>
  </div>;
}
