import { money, percent } from "../engine";
import { Badge, Button, PageHeading, Panel, Progress } from "../ui";

const toneForHealth = (health) => health === "On track" ? "success" : health === "At risk" ? "warning" : "danger";

export function Scenarios({ state, comparisons, updateScenario, applyScenario }) {
  const { scenario } = state;
  return <div className="page">
    <PageHeading eyebrow="What-if planning" title="Recovery scenarios and trade-offs" text="Model contractor capacity, deadline changes, and team velocity before you commit to a client-facing recovery plan."/>
    <div className="scenario-controls"><Panel eyebrow="Active planning assumptions" title="Adjust the current plan"><div className="scenario-fields"><label>Team velocity <input type="range" min="0.75" max="1.25" step="0.01" value={scenario.capacityMultiplier} onChange={(event) => updateScenario({ capacityMultiplier: Number(event.target.value) })}/><strong>{percent(scenario.capacityMultiplier * 100)}</strong><small>Applies to weekly team capacity</small></label><label>Deadline extension <input type="range" min="0" max="30" step="1" value={scenario.deadlineExtensionDays} onChange={(event) => updateScenario({ deadlineExtensionDays: Number(event.target.value) })}/><strong>{scenario.deadlineExtensionDays} days</strong><small>Moves the target deadline</small></label><label>Contractor capacity <input type="range" min="10" max="45" step="1" value={scenario.contractorHours} onChange={(event) => updateScenario({ contractorHours: Number(event.target.value) })}/><strong>{scenario.contractorHours}h / week</strong><small>Used only when specialist is enabled</small></label><label>Contractor hourly cost <input type="number" min="0" value={scenario.contractorRate} onChange={(event) => updateScenario({ contractorRate: Number(event.target.value) || 0 })}/><strong>{money(scenario.contractorRate)}</strong><small>Scenario-only internal delivery rate</small></label></div><button className={scenario.addContractor ? "contractor-toggle selected" : "contractor-toggle"} onClick={() => updateScenario({ addContractor: !scenario.addContractor })}><i>{scenario.addContractor ? "✓" : "+"}</i><div><strong>Add a flex delivery specialist</strong><span>Multi-skill contractor for Backend, API, AI, Automation, and QA work.</span></div></button></Panel><Panel eyebrow="Scenario logic" title="How the engine decides"><div className="scenario-rules"><span><b>1</b> Match required task skills to each employee</span><span><b>2</b> Reward available capacity and relevant seniority</span><span><b>3</b> Penalize high cost and existing workload</span><span><b>4</b> Schedule after dependencies and employee availability</span><span><b>5</b> Score deadline, budget, blocker, and overload risk</span></div></Panel></div>
    <Panel eyebrow="Comparison board" title="Choose a response path" description="Each card runs the same delivery workload through a different staffing and deadline condition."><div className="scenario-grid">{comparisons.map((item) => { const plan = item.plan; return <article key={item.id} className={item.id === "baseline" ? "scenario-card current" : "scenario-card"}><div className="scenario-card-top"><span>{item.label}</span><Badge tone={toneForHealth(plan.risk.health)}>{plan.risk.health}</Badge></div><p>{item.note}</p><strong>{money(plan.forecastCost)}</strong><small>forecast delivery cost</small><div className="scenario-data"><span>Complete <b>{plan.completionDate}</b></span><span>Risk <b>{plan.risk.score}/100</b></span><span>Margin <b>{plan.margin.toFixed(1)}%</b></span><span>Slip <b>{plan.slipDays} days</b></span></div><Progress value={plan.risk.score} tone={plan.risk.health === "On track" ? "green" : plan.risk.health === "At risk" ? "gold" : "red"}/><Button variant={item.id === "baseline" ? "outline" : "primary"} onClick={() => applyScenario(item.id)}>{item.id === "baseline" ? "Use baseline" : "Apply scenario"}</Button></article>; })}</div></Panel>
    <div className="scenario-insights"><Panel eyebrow="Scenario impact" title="Current plan versus best recovery option"><div className="impact-list">{comparisons.slice(1).map((item) => { const baseline = comparisons[0].plan; const plan = item.plan; return <div key={item.id}><strong>{item.label}</strong><span>{plan.slipDays - baseline.slipDays <= 0 ? `${Math.abs(plan.slipDays - baseline.slipDays)} fewer slip days` : `${plan.slipDays - baseline.slipDays} more slip days`}</span><span>{money(plan.forecastCost - baseline.forecastCost)} cost difference</span><span>{Math.round(plan.risk.score - baseline.risk.score)} risk change</span></div>; })}</div></Panel><Panel eyebrow="Decision support" title="Suggested next move"><div className="decision-card"><i>{comparisons[0].plan.risk.health === "Delayed" ? "!" : "✓"}</i><div><strong>{comparisons[0].plan.risk.health === "Delayed" ? "Protect the deadline before committing a client update" : "Current plan can be managed with active monitoring"}</strong><p>{comparisons[0].plan.blockedTasks.length ? "Resolve blocked client or integration dependencies first, then review contractor capacity." : "Use a recovery option only if the planned capacity or client deadline changes."}</p></div></div></Panel></div>
  </div>;
}
