import { useState } from "react";
import { SKILLS } from "../data";
import { dateLabel, money, percent } from "../engine";
import { Avatar, Badge, Button, PageHeading, Panel, Progress } from "../ui";

export function Team({ state, plan, updateEmployee, addEmployee }) {
  const [showAdd, setShowAdd] = useState(false);
  const [draft, setDraft] = useState({ name: "", role: "Delivery Specialist", initials: "", skills: [], hourlyRate: 75, weeklyCapacity: 28, committedHours: 0, availability: "Available", seniority: 2 });
  const toggleSkill = (skill) => setDraft((current) => ({ ...current, skills: current.skills.includes(skill) ? current.skills.filter((item) => item !== skill) : [...current.skills, skill] }));
  function submit(event) {
    event.preventDefault();
    if (!draft.name.trim() || !draft.skills.length) return;
    addEmployee({ ...draft, name: draft.name.trim(), initials: draft.initials.trim() || draft.name.split(" ").map((word) => word[0]).slice(0, 2).join("").toUpperCase(), hourlyRate: Number(draft.hourlyRate) || 0, weeklyCapacity: Number(draft.weeklyCapacity) || 1, committedHours: Number(draft.committedHours) || 0 });
    setDraft({ name: "", role: "Delivery Specialist", initials: "", skills: [], hourlyRate: 75, weeklyCapacity: 28, committedHours: 0, availability: "Available", seniority: 2 });
    setShowAdd(false);
  }
  return <div className="page">
    <PageHeading eyebrow="Delivery workforce" title="Team capacity and skill coverage" text="Use current commitments, weekly capacity, cost rate, skills, and availability to decide who should carry the next piece of delivery work." action={<Button onClick={() => setShowAdd((value) => !value)}>{showAdd ? "Close employee form" : "Add employee"}</Button>}/>
    {showAdd && <Panel eyebrow="Capacity input" title="Add delivery team member"><form className="team-form" onSubmit={submit}><label>Name<input required value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} placeholder="Employee name"/></label><label>Role<input required value={draft.role} onChange={(event) => setDraft((current) => ({ ...current, role: event.target.value }))} placeholder="Role title"/></label><label>Initials<input value={draft.initials} onChange={(event) => setDraft((current) => ({ ...current, initials: event.target.value }))} placeholder="AB"/></label><label>Hourly cost<input type="number" value={draft.hourlyRate} onChange={(event) => setDraft((current) => ({ ...current, hourlyRate: event.target.value }))}/></label><label>Weekly capacity<input type="number" value={draft.weeklyCapacity} onChange={(event) => setDraft((current) => ({ ...current, weeklyCapacity: event.target.value }))}/></label><label>Committed hours<input type="number" value={draft.committedHours} onChange={(event) => setDraft((current) => ({ ...current, committedHours: event.target.value }))}/></label><label>Availability<select value={draft.availability} onChange={(event) => setDraft((current) => ({ ...current, availability: event.target.value }))}><option>Available</option><option>Limited</option><option>Unavailable</option></select></label><label>Seniority<select value={draft.seniority} onChange={(event) => setDraft((current) => ({ ...current, seniority: Number(event.target.value) }))}><option value="1">Associate</option><option value="2">Mid-level</option><option value="3">Senior</option></select></label><div className="wide-field"><span className="input-label">Skills</span><div className="skill-picker">{SKILLS.map((skill) => <button type="button" className={draft.skills.includes(skill) ? "selected" : ""} key={skill} onClick={() => toggleSkill(skill)}>{draft.skills.includes(skill) ? "✓ " : "+ "}{skill}</button>)}</div></div><div className="form-actions"><Button type="submit">Add employee</Button><Button type="button" variant="outline" onClick={() => setShowAdd(false)}>Cancel</Button></div></form></Panel>}
    <div className="team-summary"><Panel eyebrow="Capacity overview" title="Forecasted team utilization"><div className="capacity-board">{plan.employeeStats.map((employee) => <article key={employee.id} className={employee.overbooked ? "overbooked" : ""}><div className="employee-card-head"><Avatar initials={employee.initials} tone={employee.overbooked ? "danger" : "gold"}/><div><strong>{employee.name}</strong><span>{employee.role}</span></div><Badge tone={employee.overbooked ? "danger" : employee.utilization > 82 ? "warning" : "success"}>{percent(employee.utilization)}</Badge></div><Progress value={employee.utilization} tone={employee.overbooked ? "red" : employee.utilization > 82 ? "gold" : "green"}/><div className="employee-card-meta"><span>{Math.round(employee.forecastWeeklyHours)}h / {Math.round(employee.weeklyCapacity * state.scenario.capacityMultiplier)}h weekly</span><span>Next free {dateLabel(employee.nextAvailable)}</span></div></article>)}</div></Panel><Panel eyebrow="Coverage signal" title="Skill depth"><div className="skill-coverage">{SKILLS.map((skill) => { const people = state.employees.filter((employee) => employee.skills.includes(skill)); return <div key={skill}><span>{skill}</span><div>{people.map((employee) => <i key={employee.id} title={employee.name}>{employee.initials}</i>)}</div><b>{people.length ? `${people.length} people` : "Coverage gap"}</b></div>; })}</div></Panel></div>
    <Panel eyebrow="Editable workforce records" title="Capacity and cost controls"><div className="team-table"><div className="team-head"><span>Employee</span><span>Skills</span><span>Rate</span><span>Capacity</span><span>Committed</span><span>Availability</span></div>{state.employees.map((employee) => { const forecast = plan.employeeStats.find((item) => item.id === employee.id); return <div className="team-row" key={employee.id}><div><Avatar initials={employee.initials}/><div><strong>{employee.name}</strong><small>{employee.role} · {employee.seniority === 3 ? "Senior" : employee.seniority === 2 ? "Mid-level" : "Associate"}</small></div></div><div className="skill-tags">{employee.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><label><span>$</span><input type="number" value={employee.hourlyRate} onChange={(event) => updateEmployee(employee.id, { hourlyRate: Number(event.target.value) || 0 })}/><small>{money(employee.hourlyRate)}/hr</small></label><label><input type="number" value={employee.weeklyCapacity} onChange={(event) => updateEmployee(employee.id, { weeklyCapacity: Number(event.target.value) || 1 })}/><small>{forecast ? percent(forecast.utilization) : "0%"} load</small></label><label><input type="number" value={employee.committedHours} onChange={(event) => updateEmployee(employee.id, { committedHours: Number(event.target.value) || 0 })}/><small>Existing work</small></label><select value={employee.availability} onChange={(event) => updateEmployee(employee.id, { availability: event.target.value })}><option>Available</option><option>Limited</option><option>Unavailable</option></select></div>; })}</div></Panel>
  </div>;
}
